// <auto-generated />
namespace CCSVolunteerMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixingSearchEntry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixingSearchEntry));
        
        string IMigrationMetadata.Id
        {
            get { return "201611240018447_FixingSearchEntry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
