// <auto-generated />
namespace CCSVolunteerMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TryingToCreateTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TryingToCreateTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201612040131282_TryingToCreateTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
